### ISSUE TITLE
v0.27.0 Uncaught (in promise) TypeError: url.parse is not a function

### ISSUE THREAD

**Issue by wxs77577** [axios/axios#4626]
#### Describe the bug
All axios based requests crashed in **v0.27.0**, but it's ok if downgrade to **v0.26.1**

#### To Reproduce
```bash
npm i axios@0.27.0
```

```js
axios.post('http://localhost:3000/api', {})
```

#### Expected behavior
No exceptions.

#### Environment
 - Axios Version [0.27.0] 
 - Adapter [e.g. XHR/HTTP]
 - Browser [e.g. Chrome, Safari]
 - Browser Version [e.g. 22]
 - Node.js Version [e.g. 13.0.1]
 - OS: [e.g. iOS 12.1.0, OSX 10.13.4]
 - Vue [3.2.25]
 - Vite [2.9.5]
 - Additional Library Versions [e.g. React 16.7, React Native 0.58.0]

#### Additional context/Screenshots
![image](https://user-images.githubusercontent.com/1990059/165245328-f0463c88-1295-4a6a-b4d4-96710c84e425.png)

**Comment by ddolcimascolo** [comment]
Hi guys,

We're bitten by this as well. Do you need any help troubleshooting?

Thx,  
David

**Comment by ddolcimascolo** [comment]
Guys,

Our CRA app does not build with v0.27.0 with the following error message, I'm suspecting it's the same issue...

```
> craco build
Creating an optimized production build...
Failed to compile.
Module not found: Error: Can't resolve 'url' in '/builds/stordata/cmdb/frontend/node_modules/axios/lib/adapters'
BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.
If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "url": require.resolve("url/") }'
	- install 'url'
If you don't want to include a polyfill, you can use an empty module like this:
	resolve.fallback: { "url": false }
```

**Comment by wxs77577** [comment]
I use `vite + vue3`, it loads ES modules in browser directly, may that's the point. Does latest version of `axios` require  some compiling tools like `webpack` or `babel` ?

**Comment by jasonsaayman** [comment]
This was a fault with the release, please try 0.27.1 this should fix these errors, if not please mention me again in a comment here.

**Comment by ddolcimascolo** [comment]
Confirmed fixed in v0.27.1. No other breaking changes I hope :crossed_fingers:

**Comment by lorand-horvath** [comment]
@jasonsaayman The 0.27.1 /dist build is even larger than 0.27.0 and it looks like it still includes the node url module, please see report https://github.com/axios/axios/issues/4629

**Comment by green-kong** [comment]
same issue. thx mate.

**Comment by jasonsaayman** [comment]
closing and looking at the build issue
