### ISSUE TITLE
[BUG] Issue 5038 is closed but not resolved

### ISSUE THREAD

**Issue by MrMaheshwari** [axios/axios#5059]
Kindly refer the same description mentioned in issue 5038.

Still getting same issue of **TypeError: axios.get is not a function (v1.1.1).**

**Comment by blackbird91** [comment]
I can confirm that I'm getting the same error on 1.1.1

**Comment by chadreed93** [comment]
In the meantime, the workaround is to use this version: https://unpkg.com/axios@0.27.2/dist/axios.min.js

**Comment by blackbird91** [comment]
working on 1.1.2

**Comment by jasonsaayman** [comment]
Should be fine now, use latest

**Comment by MrMaheshwari** [comment]
Yes, is working now. Issue is resolved.
