### ISSUE TITLE
TypeError: ']' expected (v1.1.0)

### ISSUE THREAD

**Issue by VictorHAS** [axios/axios#5039]
#### Describe the bug
Started getting the following when upgraded to axios latest version.

#### To Reproduce
Use latest version of axios in package.json
```js
/node_modules/axios/index.d.ts
TypeScript error in /node_modules/axios/index.d.ts(6,18):
']' expected.  TS1005

    4 |
    5 | type MethodsHeaders = {
  > 6 |   [Key in Method as Lowercase<Key>]: AxiosHeaders;
      |                  ^
    7 | };
    8 |
    9 | interface CommonHeaders  {
```

#### Expected behavior
In an ideal world, the nodejs app would have started without error.

#### Environment
 - Axios Version 1.1.0

#### Additional context/Screenshots
N/A

**Comment by YosrySWE** [comment]
+1

**Comment by Aijeyomah** [comment]
@VictorHAS @YosrySWE I would like to work in this

**Comment by jasonsaayman** [comment]
Will look into it

**Comment by YosrySWE** [comment]
check on TypeScript version; if it is less than 4, update it to 4.8.4
it was 3.5.3 for me

**Comment by jasonsaayman** [comment]
Hi :wave:

Please try the latest pre-release by running the following:

```bash
npm i axios@1.2.0-alpha.1
```

Please provide feedback in either the pinned issue or the discussion thread 🧵

**Comment by pabloFuente** [comment]
I hace also encountered this error. The TypeScript version of my NPM project is in fact 3.5.3, but for other reason I cannot udpate it right now. So I am stuck with axios 0.27.2.

```
ERROR in ../node_modules/axios/index.d.ts:6:18 - error TS1005: ']' expected.

6   [Key in Method as Lowercase<Key>]: AxiosHeaders;
                   ~~
../node_modules/axios/index.d.ts:6:21 - error TS1005: ';' expected.

6   [Key in Method as Lowercase<Key>]: AxiosHeaders;
                      ~~~~~~~~~
../node_modules/axios/index.d.ts:6:35 - error TS1005: '(' expected.

6   [Key in Method as Lowercase<Key>]: AxiosHeaders;
                                    ~
../node_modules/axios/index.d.ts:6:36 - error TS1135: Argument expression expected.

6   [Key in Method as Lowercase<Key>]: AxiosHeaders;
                                     ~
../node_modules/axios/index.d.ts:6:50 - error TS1005: ')' expected.

6   [Key in Method as Lowercase<Key>]: AxiosHeaders;
                                                   ~
../node_modules/axios/index.d.ts:7:1 - error TS1128: Declaration or statement expected.

7 };
```

**Comment by shu1gin** [comment]
+1

**Comment by lswqwe12** [comment]
I encountered the same error. 
Typescript@4.0.8
angular@10.2.5
axios@1.2.2

**Comment by ajimae** [comment]
> check on TypeScript version; if it is less than 4, update it to 4.8.4 it was 3.5.3 for me, try this

Not working on TypeScript version "4.0.5"

Take a look at this open issue #5428

**Comment by ajw015** [comment]
It worked for me when I upgraded to typescript `4.9.4`

**Comment by obianaghag** [comment]
Wow @ajw015 this worked for me as well. Thanks

**Comment by dai-joey** [comment]
it works for me to turn my axios to v0.20.0
