### ISSUE TITLE
TypeError: axios.get is not a function (v1.1.0)

### ISSUE THREAD

**Issue by addisonhardy** [axios/axios#5038]
#### Describe the bug
The new version of axios (v1.1.0) is throwing an error for `axios.get`: `TypeError: axios.get is not a function`.

Note: This issue was not present in v1.0.0

#### To Reproduce
Include axio v1.1.0 via a `<script>` tag, and then reference it directly via `axios.get()`

```html
<script src="https://unpkg.com/axios@1.1.0/dist/axios.min.js"></script>
<script>
    axios.get(...)
</script>
```

#### Expected behavior
`axios.get` should be a valid function.

#### Environment
 - Axios Version 1.1.0

**Comment by addisonhardy** [comment]
Note that this is when including axios via a `<script>` tag, and then referencing it directly.  It looks like the `get` function is available via `axios.default.get` - was this an intended change?

**Comment by pablo-the-dev** [comment]
I am experience this breaking change, my production app is broken and unusable to my clients.

**Comment by CarlLindqvist** [comment]
Me three. Prod is down. Got woken up here by confused users

**Comment by addisonhardy** [comment]
Pinning `axios` back to v0.27.2 (https://unpkg.com/axios@0.27.2/dist/axios.min.js) does resolve the issue if anyone is looking for a temporary solution.

**Comment by pablo-the-dev** [comment]
> Pinning `axios` back to v0.27.2 (https://unpkg.com/axios@0.27.2/dist/axios.min.js) does resolve the issue if anyone is looking for a temporary solution.

I've tested and confirmed going to version 1.0.0 also works, problem is that will require app store review.  IMO the devs should roll the distribution back.

**Comment by rwging** [comment]
We are also experiencing this issue, and will have to wait for app store review for a fix unless the hosted code can be fixed.  Adding to the vote for roll back to 1.0

**Comment by addisonhardy** [comment]
> I've tested and confirmed going to version 1.0.0 also works, problem is that will require app store review. IMO the devs should roll the distribution back.

It looks like version 1.0.0 had an issue affecting commonjs/umd exports (`axios.default`).  I think this regression happened during the work to fix that issue.

**Comment by DevMukhtarr** [comment]
It affected my app in production too, axios is not a function.

**Comment by addisonhardy** [comment]
@SaaymanJason Tagging for visibility

**Comment by addisonhardy** [comment]
@jasonsaayman Tagging for visibility.

**Comment by andrewsaraceni** [comment]
Confirmed as breaking production applications on my end as well.  This is a big miss in testing coverage for a library like this.

**Comment by jkira** [comment]
Also having multiple broken production apps here.

**Comment by alessondejesus** [comment]
same, my production environment has broken

**Comment by christophorusdou** [comment]
My production has broken as well.

**Comment by tony-brandner** [comment]
Major issues on our sites, had to change and pin to 0.27.0

**Comment by nicholasgomez-dev** [comment]
Experiencing issues as well on production apps. 
Error: "axios is not a function"

**Comment by gytisz3** [comment]
For those using unpkg CDN, switching to jsDelivr as the source seems to help
`https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js`

**Comment by MMtinker** [comment]
same here! All apps using axios are broken!

**Comment by corey-c** [comment]
For anyone calling the non version specific unpkg CDN link you can switch to this version to fix the current problem

https://unpkg.com/axios@1.0.0/dist/axios.min.js

**Comment by addisonhardy** [comment]
At the time of this comment:
- https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js: serving axios version 1.0.0
- https://unpkg.com/axios/dist/axios.min.js: serving axios version 1.1.0

**Comment by Bradford401** [comment]
axios.post not working as well

**Comment by jqr108** [comment]
gotta git get imo

**Comment by AnnAngela** [comment]
I found out that the `module.exports` of axios@1.1.0 has been changed from axios@1.0.0, which introduced in #5003 and #5030. These PR made the `module.exports` completely changed showing in https://github.com/axios/axios/compare/v1.0.0...v1.1.0#diff-e114a79086c5cde98bca3f766534b7f86a1093035560390daa3a2192047289d9R3756-R3760

@jasonsaayman I think this is an incompatible breaking change that should be reverted or disclosed.

**Comment by AnnAngela** [comment]
To be honest, these changes addressed type definition issue indeed, I don't need JSDoc comment at all.
```
/**
 * @type {axios.AxiosStatic}
 */
```

**Comment by masa172** [comment]
An error "TypeError: axios.get is not a function" on the latest version 1.1.0 was detected yesterday. 

To use the version 1.0.0 instead is better way to avoid the error for now.

Hope to resolve this issue immediately.

**Comment by craftxbox** [comment]
Can repro. This is causing major issues with an electron app of mine. Axios is used via unpkg versionless inside of the asar and there is no way to notify users to update  as all requests to autoupdater are handled through axios... This should be reverted, and such a breaking change should have been communicated well in advance (and NOT distributed under a semver minor change!!)

**Comment by danveb** [comment]
Thank you! 
Just downgraded axios back to v1.0.0.
Was playing around with an API with v1.1.0 and all hell broke loose.

**Comment by eliecer2000** [comment]
+1 :(

**Comment by quarantaquatro** [comment]
This just killed 3 of my client's applications with this problem. I downloaded the old 1.0.0 and used it locally on all applications until this is solved in 1.1.0. I recommend for everyone do the same.

**Comment by bukhoy** [comment]
accept +1 :c

**Comment by jasonsaayman** [comment]
Will start looking into this today, once again sorry about this.

**Comment by Legomegger** [comment]
thanks guys, we thought that it is our PR that broke prod, changed to 1.0.0 version

**Comment by jilliansalloum** [comment]
> Will start looking into this today, once again sorry about this.

i am supposed to film a demo of my website I built that not is not functioning becuase of this. I have a few hours. How long will the repair take??

**Comment by C0dekid** [comment]
> > Will start looking into this today, once again sorry about this.
> 
> i am supposed to film a demo of my website I built that not is not functioning becuase of this. I have a few hours. How long will the repair take??

You could use a different version for now if that's possible for you. Version `1.0.0` seems to be close and is just one version downgraded.

```
https://cdnjs.cloudflare.com/ajax/libs/axios/1.0.0/axios.min.js
```

**Comment by jilliansalloum** [comment]
> > > Will start looking into this today, once again sorry about this.
> > 
> > 
> > i am supposed to film a demo of my website I built that not is not functioning becuase of this. I have a few hours. How long will the repair take??
> 
> You could temporarily use a different version for now if that's possible for you. Version `1.0.0` seems to be close and is just one version below the latest version.
> 
> ```
> https://cdnjs.cloudflare.com/ajax/libs/axios/1.0.0/axios.min.js
> ```

i tried this and i  ran npm install axios@1.0.0, and even tried  npm install axios@0.27.2 and neither is solving my issue

**Comment by ScottDurkin** [comment]
Production is broken for me as well.. Any sign of a fix incoming?

**Comment by Chicooz** [comment]
ROLL BACK TO 0.27

**Comment by rohit-gh** [comment]
@naveensky tagging you for reach / visibility

**Comment by Chicooz** [comment]
using @AnnAngela 's findings `const axios = require("axios").default;` solved it for me

**Comment by AnnAngela** [comment]
> using @AnnAngela 's findings `const axios = require("axios").default;` solved it for me, however this would break any living app these elements should go back to root

Thanks for your mention, I updated the original comment to make the suggestion more understandable.

**Comment by chip20014u** [comment]
Using the axios@1.0.0 version and require("axios").default; solved it for me

**Comment by sagar-thakkar-dev** [comment]
I am also getting these issues on the newer version. 1.1.0. A fallback to the 1.0.0 version is temporarily worked. 

Refer below thread for a more detailed explanation. 
https://github.com/axios/axios/issues/5053#issuecomment-1271218959

**Comment by Eerovil** [comment]
A major breaking change to a project this big is not acceptable. This should have been handled differently:

* Deprecate the functions MONTHS in advance, giving warnings when used. Finally in the breaking version, the breaking change should give a verbose error message when used.
* Use a major version for breaking changes (i.e. `1.0.0` -> `2.0.0`
* Provide a migration guide to fix these changes.

**Comment by khangtv123** [comment]
please revert it.

**Comment by DevMukhtarr** [comment]
If you are using cdn this version will fix it 
` <script src="https://unpkg.com/axios@0.27.2/dist/axios.min.js"></script> `
Heard 1.0 also fix this error

**Comment by jasonsaayman** [comment]
I am going to have a fix out in the next hour

**Comment by vipin733** [comment]
bhai jaldi fix kar do , client ne kand asamjh liya

**Comment by dedanirungu** [comment]
Also affect I had to revert to (https://unpkg.com/axios@0.27.2/dist/axios.min.js)

**Comment by AnnAngela** [comment]
Update my https://github.com/axios/axios/issues/5038#issuecomment-1270982590 for browser users

**Comment by jasonsaayman** [comment]
Update to v1.1.1 this should slove the issue

**Comment by guiolmar** [comment]
> Update to v1.1.1 this should slove the issue

I'm going to try it!

**Comment by GeordieStew** [comment]
> Update to v1.1.1 this should slove the issue

Thanks. Any idea how long these things take to reflect on CDNs generally? We're not pinned to a version. I've pinned back to 1.0.0 where possible but have some complex sites that rely on "latest version" from CDN. "https://unpkg.com/axios/dist/axios.min.js"

**Comment by guiolmar** [comment]
> Update to v1.1.1 this should slove the issue

It seems that the "axios.get is not a function" error is still on version 1.1.1

**Comment by ScottDurkin** [comment]
> Update to v1.1.1 this should slove the issue

Still have "axios.get is not a function" error while using "https://unpkg.com/axios/dist/axios.min.js".

**Comment by anasau** [comment]
Also getting 'Axios.post is not a function' when using "https://unpkg.com/axios/dist/axios.min.js".

**Comment by kloetje** [comment]
We are also having this issue with 'https://az416426.vo.msecnd.net/scripts/a/ai.0.js'

**Comment by AnnAngela** [comment]
@jasonsaayman In 1.1.1, the export is still in `default` =。=

![image](https://user-images.githubusercontent.com/9762652/194523903-3cc6ba53-89fc-446d-92ef-9d8404631f10.png)

**Comment by JoeyFenny** [comment]
Why you guys don't point to a specific version is far beyond me.

**Comment by jasonsaayman** [comment]
Yeah I see, it seems the browser bundle was also affected will fix

**Comment by ScottDurkin** [comment]
> Why you guys don't point to a specific version is far beyond me.

I have to agree even though I am guilty of this. Learn't a lesson today.

**Comment by masa172** [comment]
Working at v1.1.2
Thanks.

**Comment by paauloedu** [comment]
I have the same problem with axios: "Uncaught TypeError: axios.get is not a function"

**Comment by meddi-oficial** [comment]
Common, we fixed prod yesterday using axios.default, and now is broken again lol. Gotta use https://unpkg.com/axios@0.27.2/dist/axios.min.js until they decide if it is going to be axios.default or axios.

**Comment by yousef-iskandar** [comment]
> I think anyone who is having this problem should really get some consultancy about how to deploy applications to prod.
> 
> I'm not trying to be condescending. I'm telling this because all your deployments are wide open to a supply-chain attack which is even worse than having your prod broken.

This is a good point, but consider the README.md explicitly encourages this usage of the package.

**Comment by bsssshhhhhhh** [comment]
> I think anyone who is having this problem should really get some consultancy about how to deploy applications to prod.
> 
> I'm not trying to be condescending. I'm telling this because all your deployments are wide open to a supply-chain attack which is even worse than having your prod broken.

More specifically:

- **Test your package upgrades _before_ deploying them to production.** Anyone in this thread complaining about production being broken clearly didn't do this. Outsourcing your QA efforts to your customers is not ideal.
- **Pin your package versions**. Just because your project currently works with one version of the package does not mean it will work with another.

**Comment by SeinopSys** [comment]
I sincerely hope every single one of those who were complaining about the 1000+ production websites this just broke have now each contributed hundreds of dollars to the maintainers of this package to recognize all the labour they have been so carelessly profiting off of so far.

**Comment by camposyan** [comment]
I'm having the same error 'axios.get is not a function'. All my requests are broken now.

**Comment by meddi-oficial** [comment]
> 
You should update your version to 1.1.2. Otherwise, you have to use axios.default.get

**Comment by Daxcor69** [comment]
1.1.2 gave me the same error, I had to go back to 1.1.0.

**Comment by foray1010** [comment]
Since the latest versions, there are two groups of users with different ways importing axios
1. `const axios = require('axios')`
2. `const axios = require('axios').default`

IMO, it would be ideal if we can find a way to support both styles, if not, we have to choose one and declare the other one invalid (which I think is `1` because `2` is stated in README)

**Comment by MauiMan1** [comment]
Following...

**Comment by arthurfiorette** [comment]
Can we lock this issue to avoid spam? They ran into this issue **(in production)** because they didn't pinned their dependencies correctly.

**Comment by Jay-Madden** [comment]
Good god y'all, pin your dependencies. If your app can't handle an outage then make sure your versions are locked.

**Comment by jasonsaayman** [comment]
Thanks for all the feedback everyone, also some great pointers here on how to manage your own software. On the way Axios should work when using it with Common JS it should always be:

```js
const axios = require('axios')
```

I will work to make sure this is always the case. I will also update all the docs etc ASAP. Lastly, I will fix the problems that seem to now exist when using Type Script. I know this was a rough release, but I will endeavour to make them more smooth from here on.

**Comment by gondar00** [comment]
Missing test case is the RCA for this issue, its best to add another test case such that this issue doesn't happen again in the future

**Comment by growthwp** [comment]
> I sincerely hope every single one of those who were complaining about the 1000+ production websites this just broke have now each contributed hundreds of dollars to the maintainers of this package to recognize all the labour they have been so carelessly profiting off of so far.

Sheesh, I imagine we'll be getting a lot of down-votes with this, because, well, who uses Github? OSS developers! However, if you can't agree with the following points, it means you're one of the people(s) I'll be describing.

I hope the author will lock this thread, because it will become a cesspool of needless arguments (good ones, however. I think. Hope). So, as someone who's personally contributed to a lot of OSS, **this is not what OSS is about.** This line of thought - yours - is objectively entitled, and it shows that you want to use OSS as a ways to market yourself/the tool. Why are you opening a project to the public, if your goal is to sell it?

We all know that 99.9% of the OSS projects are just that. Ways to market yourself. Why would anybody in their right mind open a project up like that? They simply lack the funds initially and/or do it as a hobby.

So, no. As someone with a lot of impactful contributions in my field, I don't think people should pay me. The work I do - and which we'll release under `growthwp` will be ground-breaking for its niche and every developer will love that they will finally no longer have to deal with a lot of stuff. **But that doesn't mean I/we are entitled to anyone's money, nor is it bad if nobody donates. We made a decision to release it as OSS.**

If you don't like OSS, just build a business? Oh, but we just go to exactly the lie in your seemingly benevolent comment - you don't want to pay for marketing and, instead, you rely on the OSS community to prop your tool up. Which is what your comment is really all about.

We couldn't have created what we'll be releasing without the OSS community. Some, we support on a monthly basis, some, we supported even from this account, even if we're in "standby/stealth" mode, but none of them had a requirement for it. They put a tool out there - it's public domain. They made that choice. If you want money, release a product and do your own marketing.

**Comment by noscripter** [comment]
What you can learn from this issue:

- you don't need axios actually, instead use XHR/Fetch or etc directly plz
- please lock up your dependencies for production environments/releases

**Comment by sarbull** [comment]
it works on my machine
