### ISSUE TITLE
Uncaught TypeError: socket.setTimeout is not a function in 1.13.[2-5] not in 1.13.1

### ISSUE THREAD

**Issue by smokhov** [axios/axios#7395]
Hello,

Some project tests started to fail after updating axios from 1.13.1 to every release 1.13.[2-5]. What's the cause and how to address it? Node 20.x, 22.x, 24x; follow-redirects 1.15.11. Does not happen in axios 1.3.1.

```
     Uncaught TypeError: socket.setTimeout is not a function
      at RedirectableRequest.destroyOnTimeout (node_modules/follow-redirects/index.js:210:12)
      at RedirectableRequest.emit (node:events:536:35)
      at eventHandlers.<computed> (node_modules/follow-redirects/index.js:49:24)
      at ClientRequest.emit (node:events:536:35)
      at tickOnSocket (node:_http_client:843:7)
      at onSocketNT (node:_http_client:906:5)
      at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
```

Thank you.

**Comment by smokhov** [comment]
I will close this as I've worked around with dummy `setTimeout()`s on sockets in the tests. Not sure what changed in 1.13.2 though to cause the behaviour.
