### ISSUE TITLE
Is the breaking change in the type definition of AxiosError as intended?

### ISSUE THREAD

**Issue by nekoya** [axios/axios#4716]
#### Describe the bug

The definition of `AxiosError` had been updated at v0.27.0.

https://github.com/axios/axios/pull/3645/files#diff-7aa4473ede4abd9ec099e87fec67fd57afafaf39e05d493ab4533acc38547eb8L124-R124

It seems compatible with the previous code, but this changeset is not based on #4186.

In v0.26.1, `AxiosError` defined as `<T = any, D = any> extends Error`.

https://github.com/axios/axios/blob/v0.26.1/index.d.ts#L139

As a result, `AxiosError` has a different type definition than `AxiosPromise` or `AxiosResponse`. The former `<T=unknown>`, the latter `<T=any>`.  I think these inconsistent definitions are undesirable.

It seems to me that this breaking change is unintentional, isn't it?

#### To Reproduce

```typescript
if (axios.isAxiosError(e)) {
  console.log(e.response.data.message)
}
```

Got an error on `e.response.data`.

>Object is of type 'unknown'.ts(2571)

#### Expected behavior
No errors occur.

#### Environment
 - Axios Version: 0.27.2

**Comment by VictorAugMiner** [comment]
I think it's intentional because if the object is an AxiosError it doesn't have response.data, because of that it shouldn't be able to access the response.data object, because of that it's unknown

Here's the definition of type unknown in the official typescript documentation [Unknown type definition](https://www.typescriptlang.org/docs/handbook/2/functions.html#unknown)

**Comment by ncasale** [comment]
+1 to the above. This is preventing an upgrade to 0.27.0 for me. All online resources point to the above error handling logic mentioned by @martinfoakes as standard practice but it no longer works with this new type definition. Downgrading to 0.26.1 fixes the issue.

**Comment by dimbslmh** [comment]
The following seems to work with v0.27:

```
if (e instanceof AxiosError) {
  console.log(e.response.data.message)
}
```

**Comment by martinfoakes** [comment]
> The following seems to work with v0.27:
> 
Can confirm this worked for me, thanks!

Also for any jest users in future coming to this thread having an issue, I had to update my Jest test files after these changes, as the mock error objects I was using were not being recognised as an actual `instanceof AxiosError` in the updated code.

So instead of something like -> 

```ts
expect.assertions(2);
apiServiceFuncSpy.mockRejectedValueOnce({
  response: { status: 409, data: { message: 'Error message' } },
});

try {
  await apiServiceFunctionBeingTestedCall(mockedDataObject);
} catch (e) {
  expect(e.message).toEqual('Error message');
  // ...all other expectations etc.
}
```

I had to have an actual `AxiosError` instance mocked to pass into the test, so updated to -> 

```ts
const customAxiosErr = new AxiosError('Error', '409', undefined, {}, {
  status: 409,
  data: { message: 'Error message' },
} as AxiosResponse);

expect.assertions(2);
apiServiceFuncSpy.mockRejectedValueOnce(customAxiosErr);

try {
  await apiServiceFunctionBeingTestedCall(mockedDataObject);
} catch (e) {
  expect(e.message).toEqual('Error message');
  // ...all other expectations etc.
}
```

**Comment by plotka** [comment]
> The following seems to work with v0.27:
> 
> ```
> if (e instanceof AxiosError) {
>   console.log(e.response.data.message)
> }
> ```

Can confirm the above works. But I had already a check like below, which is not working anymore (meaning throwing Typescript error). Shouldn't it work too?
```js
 if (axios.isAxiosError(e)) {
   console.log(e.response.data.message)
 }
 ```

**Comment by martinfoakes** [comment]
> Can confirm the above works. But I had already a check like below, which is not working anymore (meaning throwing Typescript error). Shouldn't it work too?
> 
> ```js
>  if (axios.isAxiosError(e)) {
>    console.log(e.response.data.message)
>  }
> ```

Not anymore, as now in  `v0.27` the `AxiosError` definition has changed from `AxiosError<T = any, D = any>` to -> `AxiosError<T = unknown, D = any>`. Which means that even after the check of `axios.isAxiosError(e)`, `e` will still be treated as type `unknown`, as the generic class type variable `T` is now default set to `unknown`

**Comment by mleister97** [comment]
Please fix!

**Comment by mwidner** [comment]
I am finding that this code throws errors:
`function handleError(error: AxiosError) {
   // do something with error.response.data.message
}`

Whereas this is fine, but my IDE complains about redundancy:

`function handleError(error: AxiosError) {
   if (error instanceof AxiosError) {
       // do something with error.response.data.message
   }
}`

This is annoying and problematic. Seems like a downgrade for the developer experience.

**Comment by AntoineDeloy** [comment]
Hello everyone, I can only confirm what everyone just said, if we add a check to be sure that `axiosError` is an `instance of` axiosError and is not `unknown` then sonarcloud is getting mad and I have a code smell, mi IDE is also getting mad, and the developer experience is broken. I stay in version 0.26 ! Sorry

**Comment by dimbslmh** [comment]
> The following seems to work with v0.27:
> 
> ```
> if (e instanceof AxiosError) {
>   console.log(e.response.data.message)
> }
> ```

For some reason, this doesn't work anymore for me. I have downgraded to v0.26.1

**Comment by mleister97** [comment]
Any updates yet?

**Comment by hyoretsu** [comment]
```
        try {
            await api.post('/users', { ...values, doctorId: user.id });
        } catch (err: AxiosError) {
            if (err.response.status === 400) {
                setError(err.response.data.message);
            }
        }
```

People actually send error messages as responses when there's an error, so its type shouldn't be `unknown`. That works totally fine, but I get `Catch clause variable type annotation must be 'any' or 'unknown' if specified.` and err is any. When I destructure it, reponse is `unknown`.

**Comment by karlosos** [comment]
My code before upgrading the package:

```typescript
export const throwApiError = (error: AxiosError) => {
  const statusCode = error.response?.status || 0;
                                                       // ^ Property 'errorCode' does not exist on type '{}'.ts(2339)
  const message =
    error.response?.data?.message ||
    error.response?.data?.reason ||
    'Error: Internal Server Error.';

  throw new ApiError({ message, statusCode });
}
```

I have fixed it by specifying the generic type to any `AxiosError<any>`.

**Comment by arananegra** [comment]
hi @jasonsaayman, are there any chances of backing up this change? As @hyoretsu said, is a common pattern to send error messages from the API so "unknown" is a problem when you have in your code base something like this:

`
.catch((reason: AxiosError) => {
		toast.error(
			reason?.response?.data?.errorMsg
			);
		})
`
