### ISSUE TITLE
Axios not working with UMD library that is used in a react application. The react application is build using react script.

### ISSUE THREAD

**Issue by meghnasamoorthy** [axios/axios#6436]
### Describe the issue

We have a library that follows **UMD** structure. The library uses axios (version 1.6.2) for api calls. While using our library in react application built using **react script**, it produces an error **axios.post/axios.get is not a function**. The library was working well with older version (0.21.1) of axios . Please provide a solution to this issue.

### Axios Version

1.6.2

### Node.js Version

18.17.0

**Comment by jasonsaayman** [comment]
Hi @meghnasamoorthy, apologies for the slow response on this one, it has been sitting in the backlog longer than it should have.

A few things before we can dig in further. The report is against 1.6.2 and we are now on 1.16.0, with quite a bit of CJS/ESM interop work having landed in between. The current `exports` map resolves browser plus `require` to `dist/browser/axios.cjs`, and that bundle exports the axios instance with `.default` self-pointing, so `require('axios').default.get(...)` should work today. Can you confirm whether you still see the same failure on 1.16.0, and if so, share a minimal reproduction repo I can clone and run. Without that I do not have enough to act on.

While I am here, two things worth flagging that may be in play:

1. The browser-globals branch of your UMD wrapper does `factory(root)`, where every other branch passes `{ axios: ... }`. If that branch ever runs, `imports.axios.get` resolves against `window` and you get exactly the "axios.get is not a function" error, regardless of the axios version. Worth checking which branch is actually being hit in your bundle, the AMD/CJS branches or the globals fallback.

2. react-scripts has been deprecated by Meta, so its webpack config is not something we can target directly, even if there is a real interop wrinkle there. If you have the flexibility to move to Vite or a direct Webpack 5 setup, that would also help us narrow down whether the issue is with Axios or the CRA build pipeline.

I will close this as stale, but happy to reopen the moment there is a fresh repro to look at.
